name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Write NPM auth code to npm_secrets
        run: |
          echo ${{ secrets.NPM_TOKEN }} >> $GITHUB_WORKSPACE/npm_secret
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          secrets: |
            "npm_secret=${{ secrets.NPM_TOKEN }}"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web-file-server-api:latest
